#version 450
#extension GL_KHR_shader_subgroup_basic: require

#define ELEMENT_SIZE 100000
#define BLOCK_SIZE 1024
#define WARP_PER_BLOCK BLOCK_SIZE/32
#define TILE_SIZE 2048
#define TILE_PER_BLOCK 1
#define DIGITS 8

layout (local_size_x = 1024) in;

layout(push_constant) uniform constants {
    uint elementCount;
} PushConstants;

// SIZE = ELEMENT_COUNT
layout(set = 0, binding = 0, std430) buffer InputKeys
{
    uint keys[];
};

// SIZE = ELEMENT_COUNT * 2
layout(set = 0, binding = 1, std430) buffer SortedIndex
{
    uint indices[];
};


layout(set = 0, binding = 2, std430) buffer restrict GlobalCounter
{
    uint gWorkgroupCounter;
    uint gDebugLogCounter;
};

float nrand( float n )
{
	return fract(sin(91.2228 * n)* 43758.5453);
}

void main()
{
    uint gid = gl_GlobalInvocationID.x;
    if(gid >= PushConstants.elementCount) return;
    keys[gid] = gid;
    indices[gid] = gid;

    if(gid == 0)
    {
        gWorkgroupCounter = 0;
        gDebugLogCounter = 0;
    }
}