#version 450
#extension GL_KHR_shader_subgroup_basic: require

#define BLOCK_SIZE 1024
#define WARP_PER_BLOCK BLOCK_SIZE/32
#define TILE_SIZE 2048
#define TILE_PER_BLOCK 1
#define DIGITS 8

layout (local_size_x = 1024) in;

layout(push_constant) uniform constants {
    uint elementCount;
} PushConstants;

// SIZE = ELEMENT_COUNT
layout(set = 0, binding = 0, std430) buffer InputKeys
{
    uint keys[];
};

// SIZE = ELEMENT_COUNT * 2
layout(set = 0, binding = 1, std430) buffer SortedIndex
{
    uint indices[];
};

void main()
{
    uint gid = gl_GlobalInvocationID.x;
    if(gid >= PushConstants.elementCount) return;
    keys[gid] = (gid % 2 == 0) ? 0 : 1;
    indices[gid] = gid;
}