layout(push_constant) uniform constants {
    vec2 outputSize;
} PushConstants;

layout ( binding = 0 ) uniform sampler2D inputImage;
layout ( binding = 1, r11f_g11f_b10f ) uniform image2D outputImage;

void main()
{
	uvec2 pos = gl_GlobalInvocationID.xy;

	// Sampler is set up to do min reduction, so this computes the minimum depth of a 2x2 texel quad
	float depth = texture(inImage, (vec2(pos) + vec2(0.5)) / imageSize).x;

	imageStore(outImage, ivec2(pos), vec4(depth));
}
