 #version 450

layout(push_constant) uniform constants {
    uint width;
    uint height;
} PushConstants;

layout ( binding = 0, rgba8 ) uniform writeonly image2D resultImage;
layout ( binding = 1, rgba32f ) uniform image2D inputImage;

layout (local_size_x =32, local_size_y =32) in;

void main()
{
    uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;

    vec2 uv = vec2((0.5 + 1.f * x) / PushConstants.width, (0.5 + 1.f * y) / PushConstants.height);
    vec4 texture_color = imageLoad(inputImage, ivec2(x, y));

    if(x>PushConstants.width || y>PushConstants.height)
        return;
    
    imageStore(resultImage, ivec2(x, y), texture_color * vec4(uv,1,1));

}