 #version 450

layout(push_constant) uniform constants {
    uint width;
    uint height;
} PushConstants;

layout ( binding = 0, rgba8 ) uniform writeonly image2D resultImage;

layout (local_size_x =32, local_size_y =32) in;

void main()
{
    uint x = gl_GlobalInvocationID.x;
    uint y = gl_GlobalInvocationID.y;

    if(x>PushConstants.width || y>PushConstants.height)
        return;
    
    imageStore(resultImage, ivec2(x, y), vec4(1.f * x / PushConstants.width, 1.f * y / PushConstants.height,1,1));

}