 #version 450
 
layout(set = 0, binding = 0, std430) buffer Positions
{
    vec4 pos[];
} positions;

layout(set = 0, binding = 1, std430) buffer Velocity
{
    vec4 vel[];
} velocities;

layout (local_size_x =32) in;

void main()
{
    positions.pos[gl_GlobalInvocationID.x] = vec4(0 ,0, 0,0);
    velocities.vel[gl_GlobalInvocationID.x] = 10 * vec4(sin(gl_GlobalInvocationID.x),cos(gl_GlobalInvocationID.x),0,0);
}
