 #version 450
 
layout(set = 0, binding = 0, std430) buffer Positions
{
    vec2 pos[];
} positions;

layout(set = 0, binding = 1, std430) buffer Velocity
{
    vec2 vel[];
} velocities;

layout (local_size_x =32) in;

void main()
{
    vec2 current_pos = positions.pos[gl_GlobalInvocationID.x];
    vec2 velocity = velocities.vel[gl_GlobalInvocationID.x];
    current_pos += 0.00001 * velocity;
    positions.pos[gl_GlobalInvocationID.x] = current_pos;
}
