 #version 450
 
layout(set = 0, binding = 0, std430) buffer Positions
{
    vec4 pos[];
} positions;

layout(set = 0, binding = 1, std430) buffer Velocity
{
    vec4 vel[];
} velocities;

layout (local_size_x =32) in;

void main()
{
    vec3 current_pos = positions.pos[gl_GlobalInvocationID.x].xyz;
    vec3 velocity = velocities.vel[gl_GlobalInvocationID.x].xyz;
    current_pos += 0.00001 * velocity;
    positions.pos[gl_GlobalInvocationID.x].xyz = current_pos;
}
